[package]
name = "unros-core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fern = "0.6"
clap = { version = "4", features = ["derive"] }
humantime = "2"
